### ISSUE TITLE
about page not found

### ISSUE THREAD

**Issue by cutebear0123** [hello1234316/work#1]
https://hello1234316.github.io/about/
at
https://hellophone.tk/#:~:text=%E4%BD%BF%E7%94%A8HTML%E9%96%8B%E7%99%BC-,%E6%9F%A5%E7%9C%8B,-%E5%85%89%E5%BD%A9%E8%97%9D%E8%A1%93%E7%B6%B2%E7%AB%99

**Comment by hello1234316** [comment]
Fixed THX
